version: '3.8'

services:
  php:
    build:
      context: _docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
      - ./public/upload:/var/www/html/public/upload
    depends_on:
      - db
    networks:
      - symfony_network

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - ./:/var/www/html
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_network

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: products
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network
    ports:
      - "3316:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: symfony_user
      PMA_PASSWORD: symfony_password
    networks:
      - symfony_network

  composer:
    build:
      context: _docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/html

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge